resources:
- components/rbac/base
- components/database/base
- components/client/base
- components/server/base

replicas:
- name: server
  count: 1
- name: client
  count: 1

# patches:
# - patch: |-
#     - op: replace
#       path: "/spec/template/spec/containers/0/resources/limits/memory"
#       value: 1Gi
#   target:
#     kind: Deployment
#     name: server
