apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- components/rbac/base
- components/database/base
- components/client/base
- components/server/base

replicas:
- name: server
  count: 1
- name: client
  count: 1
