apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- components/rbac/base
- components/database/base
- components/client/base
- components/server/base

replicas:
- count: 1
  name: server
- count: 1
  name: client
images:
- digest: sha256:31a08cfbd32a47a6b9592d9dd5fa3897f9a0ccae
  name: server
