apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- components/rbac/base
- components/database/base
- components/client/base
- components/server/base

replicas:
- count: 1
  name: server
- count: 1
  name: client
images:
- digest: sha256:sha256:61604b67b7971d10b17716c77e74dc083ba7c222c81076f552f5d1ee625e61d0
  name: quay.io/gnunn/server
